INSERT INTO compound (id, name, scale) VALUES
('dinitrophenol', '2,4-Dinitrophenol', 'mg'),
('aceticAcid', 'Acetic acid', 'ml'),
('aceticAnhydride', 'Acetic anhydride', 'ml'),
('acetone', 'Acetone', 'ml'),
('acetonitrile', 'Acetonitrile', 'ml'),
('acetophenone', 'Acetophenone', 'ml'),
('acetaldehyde', 'Acetaldehyde', 'ml'),
('alizarinSodiumSulfonate', 'Alizarin sodium sulfonate', 'mg'),
('alizarinYellow', 'Alizarin yellow', 'mg'),
('alizarinYellowR', 'Alizarin yellow R', 'mg'),
('aluminum', 'Aluminum', 'mg'),
('aluminumChloride', 'Aluminum chloride', 'mg'),
('aluminumSulfate', 'Aluminum sulfate', 'mg'),
('ammonia', 'Ammonia', 'ml'),
('ammoniumBuffers', 'Ammonium buffers', 'ml'),
('ammoniumChloride', 'Ammonium chloride', 'mg'),
('ammoniumHydroxide', 'Ammonium hydroxide', 'ml'),
('ammoniumNitrate', 'Ammonium nitrate', 'mg'),
('ammoniumPersulfate', 'Ammonium persulfate', 'mg'),
('ammoniumSulfate', 'Ammonium sulfate', 'mg'),
('amylAcetate', 'Amyl acetate', 'ml'),
('aniline', 'Aniline', 'ml'),
('anisole', 'Anisole', 'ml'),
('azolitmin', 'Azolitmin', 'mg'),
('bariumCarbonate', 'Barium carbonate', 'mg'),
('bariumChloride', 'Barium chloride', 'mg'),
('bariumHydroxide', 'Barium hydroxide', 'mg'),
('baeyersReagent', 'Baeyer''s reagent', 'ml'),
('bicineBuffer', 'Bicine buffer', 'mg'),
('bicarbonateBuffers', 'Bicarbonate buffers', 'ml'),
('benedictsReagent', 'Benedict''s reagent', 'ml'),
('benzaldehyde', 'Benzaldehyde', 'ml'),
('benzene', 'Benzene', 'ml'),
('benzylAlcohol', 'Benzyl alcohol', 'ml'),
('benzoicAcid', 'Benzoic acid', 'mg'),
('borateBuffers', 'Borate buffers', 'mg'),
('boricAcid', 'Boric acid', 'mg'),
('boron', 'Boron', 'mg'),
('bradysReagent', 'Brady''s reagent', 'ml'),
('bromine', 'Bromine', 'ml'),
('bromocresolGreenMethylRed', 'Bromocresol Green / Methyl Red', 'mg'),
('bromocresolGreen', 'Bromocresol green', 'mg'),
('bromocresolPurple', 'Bromocresol purple', 'mg'),
('bromothymolBlue', 'Bromothymol blue', 'mg'),
('butane', 'Butane', 'ml'),
('butanol', 'Butanol', 'ml'),
('butanone', 'Butanone', 'ml'),
('butylAcetate', 'Butyl acetate', 'ml'),
('butyricAcid', 'Butyric acid', 'ml'),
('chesBuffer', 'CHES buffer', 'mg'),
('cadmiumSulfate', 'Cadmium sulfate', 'mg'),
('cacodylateBuffer', 'Cacodylate buffer', 'mg'),
('calcium', 'Calcium', 'mg'),
('calciumCarbonate', 'Calcium carbonate', 'mg'),
('calciumChloride', 'Calcium chloride', 'mg'),
('calciumCyanide', 'Calcium cyanide', 'mg'),
('calciumHydroxide', 'Calcium hydroxide', 'mg'),
('carbon', 'Carbon', 'mg'),
('carbonTetrachloride', 'Carbon tetrachloride', 'ml'),
('carbonate', 'Carbonate', 'mg'),
('carbonicAcid', 'Carbonic acid', 'ml'),
('chlorine', 'Chlorine', 'ml'),
('chloroform', 'Chloroform', 'ml'),
('chlorphenolRed', 'Chlorphenol red', 'mg'),
('cholesterol', 'Cholesterol', 'mg'),
('chromicAcid', 'Chromic acid', 'ml'),
('citrateBuffers', 'Citrate buffers', 'mg'),
('citricAcid', 'Citric acid', 'mg'),
('cobalt', 'Cobalt', 'mg'),
('cobaltChloride', 'Cobalt chloride', 'mg'),
('cobaltNitrate', 'Cobalt nitrate', 'mg'),
('collinsReagent', 'Collins reagent', 'mg'),
('congoRed', 'Congo Red', 'mg'),
('copper', 'Copper', 'mg'),
('copperSulfate', 'Copper sulfate', 'mg'),
('copperIISulfate', 'Copper(II) Sulfate', 'mg'),
('cresolRed', 'Cresol red', 'mg'),
('cresolphthalein', 'Cresolphthalein', 'mg'),
('cyclohexanol', 'Cyclohexanol', 'ml'),
('cyclohexanone', 'Cyclohexanone', 'ml'),
('cyclohexylamine', 'Cyclohexylamine', 'ml'),
('dessMartinPeriodinane', 'Dess–Martin periodinane', 'mg'),
('diazoViolet', 'Diazo violet', 'mg'),
('diborane', 'Diborane', 'ml'),
('dichlorofluorescein', 'Dichlorofluorescein', 'mg'),
('dichloromethane', 'Dichloromethane', 'ml'),
('dicyclohexylcarbodiimide', 'Dicyclohexylcarbodiimide', 'mg'),
('diethylamine', 'Diethylamine', 'ml'),
('diethylEther', 'Diethyl ether', 'ml'),
('diisobutylaluminiumHydride', 'Diisobutylaluminium hydride', 'ml'),
('dimethylEther', 'Dimethyl ether', 'ml'),
('dimethylSulfide', 'Dimethyl sulfide', 'ml'),
('dimethylamine', 'Dimethylamine', 'ml'),
('dimethylformamide', 'Dimethylformamide', 'ml'),
('dimethylSulfoxide', 'Dimethyl sulfoxide', 'ml'),
('dioxane', 'Dioxane', 'ml'),
('distilledWater', 'Distilled water', 'ml'),
('eriochromeBlackT', 'Eriochrome black T', 'mg'),
('ethanol', 'Ethanol', 'ml'),
('ethanolamine', 'Ethanolamine', 'ml'),
('ethylAcetate', 'Ethyl acetate', 'ml'),
('ethylEther', 'Ethyl ether', 'ml'),
('ethylamine', 'Ethylamine', 'ml'),
('ethyleneGlycol', 'Ethylene glycol', 'ml'),
('ethylenediaminetetraaceticAcid', 'Ethylenediaminetetraacetic acid', 'mg'),
('fehlingsReagent', 'Fehling''s reagent', 'ml'),
('fentonsReagent', 'Fenton''s reagent', 'ml'),
('ferroin', 'Ferroin', 'mg'),
('fluorine', 'Fluorine', 'ml'),
('formaldehyde', 'Formaldehyde', 'ml'),
('formicAcid', 'Formic acid', 'ml'),
('glycerin', 'Glycerin', 'ml'),
('grignardReagents', 'Grignard reagents', 'ml'),
('hepesBuffer', 'HEPES buffer', 'mg'),
('heptane', 'Heptane', 'ml'),
('hexane', 'Hexane', 'ml'),
('hydrogen', 'Hydrogen', 'ml'),
('hydrogenPeroxide', 'Hydrogen peroxide', 'ml'),
('hydrobromicAcid', 'Hydrobromic acid', 'ml'),
('hydrochloricAcid', 'Hydrochloric acid', 'ml'),
('hydrofluoricAcid', 'Hydrofluoric Acid', 'ml'),
('indigoCarmine', 'Indigo Carmine', 'mg'),
('iodine', 'Iodine', 'mg'),
('iodineSolution', 'Iodine solution', 'ml'),
('iron', 'Iron', 'mg'),
('ironSulfide', 'Iron sulfide', 'mg'),
('ironIISulfate', 'Iron(II) sulfate', 'mg'),
('ironIIIChloride', 'Iron(III) chloride', 'mg'),
('isopentylAcetate', 'Isopentyl acetate', 'ml'),
('isopropanol', 'Isopropanol', 'ml'),
('lauricAcid', 'Lauric acid', 'mg'),
('lead', 'Lead', 'mg'),
('leadAcetate', 'Lead acetate', 'mg'),
('leadNitrate', 'Lead nitrate', 'mg'),
('leadSulfide', 'Lead sulfide', 'mg'),
('lithium', 'Lithium', 'mg'),
('lithiumAluminumHydride', 'Lithium aluminum hydride', 'mg'),
('lithiumHydroxide', 'Lithium hydroxide', 'mg'),
('lucasReagent', 'Lucas reagent', 'ml'),
('mopsBuffer', 'MOPS buffer', 'mg'),
('magnesium', 'Magnesium', 'mg'),
('magnesiumHydroxide', 'Magnesium hydroxide', 'mg'),
('magnesiumSulfate', 'Magnesium sulfate', 'mg'),
('manganese', 'Manganese', 'mg'),
('mercury', 'Mercury', 'ml'),
('mercuryAcetate', 'Mercury acetate', 'mg'),
('mercuryIIChloride', 'Mercury(II) chloride', 'mg'),
('mesBuffer', 'MES buffer', 'mg'),
('methanol', 'Methanol', 'ml'),
('methanolamine', 'Methanolamine', 'ml'),
('methylOrange', 'Methyl orange', 'ml'),
('methylOrangeXyleneCyanol', 'Methyl orange - Xylene Cyanol', 'mg'),
('methylRed', 'Methyl red', 'mg'),
('methylSalicylate', 'Methyl salicylate', 'ml'),
('methylViolet', 'Methyl violet', 'mg'),
('methylYellow', 'Methyl yellow', 'mg'),
('methylcyclohexane', 'Methylcyclohexane', 'ml'),
('methyleneChloride', 'Methylene chloride', 'ml'),
('morpholine', 'Morpholine', 'ml'),
('myristicAcid', 'Myristic acid', 'mg'),
('nBromosuccinimide', 'N-Bromosuccinimide', 'mg'),
('nileBlue', 'Nile blue', 'mg'),
('ninhydrin', 'Ninhydrin', 'mg'),
('nitramine', 'Nitramine', 'mg'),
('nitricAcid', 'Nitric acid', 'ml'),
('nitrobenzene', 'Nitrobenzene', 'ml'),
('nitrogen', 'Nitrogen', 'ml'),
('neutralRed', 'Neutral red', 'mg'),
('nickel', 'Nickel', 'mg'),
('nickelHydroxide', 'Nickel hydroxide', 'mg'),
('nickelIIChloride', 'Nickel(II) chloride', 'mg'),
('octanol', 'Octanol', 'ml'),
('osmiumTetroxide', 'Osmium tetroxide', 'mg'),
('oxalicAcid', 'Oxalic acid', 'mg'),
('oxalylChloride', 'Oxalyl chloride', 'ml'),
('oxygen', 'Oxygen', 'ml'),
('pipesBuffer', 'PIPES buffer', 'mg'),
('palmiticAcid', 'Palmitic acid', 'mg'),
('palladium', 'Palladium', 'mg'),
('pentamethoxyRed', 'Pentamethoxy red', 'mg'),
('pentanoicAcid', 'Pentanoic acid', 'ml'),
('perchloricAcid', 'Perchloric acid', 'ml'),
('periodicAcid', 'Periodic acid', 'mg'),
('petroleumEther', 'Petroleum ether', 'ml'),
('phenol', 'Phenol', 'mg'),
('phenolRed', 'Phenol red', 'mg'),
('phenolphthalein', 'Phenolphthalein', 'mg'),
('phosphateBuffers', 'Phosphate buffers', 'mg'),
('phosphoricAcid', 'Phosphoric acid', 'ml'),
('phosphorus', 'Phosphorus', 'mg'),
('platinum', 'Platinum', 'mg'),
('poirriersBlue', 'Poirrier''s blue', 'mg'),
('potassium', 'Potassium', 'mg'),
('potassiumBromide', 'Potassium bromide', 'mg'),
('potassiumChlorate', 'Potassium chlorate', 'mg'),
('potassiumChloride', 'Potassium chloride', 'mg'),
('potassiumChromate', 'Potassium chromate', 'mg'),
('potassiumCyanide', 'Potassium cyanide', 'mg'),
('potassiumDichromate', 'Potassium dichromate', 'mg'),
('potassiumFerrocyanide', 'Potassium ferrocyanide', 'mg'),
('potassiumHydroxide', 'Potassium hydroxide', 'mg'),
('potassiumIodide', 'Potassium iodide', 'mg'),
('potassiumNitrate', 'Potassium nitrate', 'mg'),
('potassiumOxalateMonohydrate', 'Potassium oxalate monohydrate', 'mg'),
('potassiumPermanganate', 'Potassium permanganate', 'mg'),
('potassiumPhosphate', 'Potassium phosphate', 'mg'),
('potassiumSulfate', 'Potassium sulfate', 'mg'),
('propanol', 'Propanol', 'ml'),
('propanoicAcid', 'Propanoic acid', 'ml'),
('propylAcetate', 'Propyl acetate', 'ml'),
('pyridine', 'Pyridine', 'ml'),
('pyrrolidine', 'Pyrrolidine', 'ml'),
('raneyNickel', 'Raney nickel', 'mg'),
('rosolicAcid', 'Rosolic acid', 'mg'),
('salicylYellow', 'Salicyl yellow', 'mg'),
('salicylicAcid', 'Salicylic acid', 'mg'),
('schiffsReagent', 'Schiff''s reagent', 'ml'),
('siliconDioxide', 'Silicon Dioxide', 'mg'),
('silver', 'Silver', 'mg'),
('silverChloride', 'Silver chloride', 'mg'),
('silverNitrate', 'Silver nitrate', 'mg'),
('sodium', 'Sodium', 'mg'),
('sodiumAcetate', 'Sodium acetate', 'mg'),
('sodiumAmide', 'Sodium amide', 'mg'),
('sodiumAzide', 'Sodium azide', 'mg'),
('sodiumBicarbonate', 'Sodium bicarbonate', 'mg'),
('sodiumBisulfite', 'Sodium bisulfite', 'mg'),
('sodiumBisulfate', 'Sodium bisulfate', 'mg'),
('sodiumBorohydride', 'Sodium borohydride', 'mg'),
('sodiumCarbonate', 'Sodium carbonate', 'mg'),
('sodiumChloride', 'Sodium chloride', 'mg'),
('sodiumCyanide', 'Sodium cyanide', 'mg'),
('sodiumHydroxide', 'Sodium hydroxide', 'mg'),
('sodiumIodide', 'Sodium iodide', 'mg'),
('sodiumNitrate', 'Sodium nitrate', 'mg'),
('sodiumNitrite', 'Sodium nitrite', 'mg'),
('sodiumSulfate', 'Sodium sulfate', 'mg'),
('sodiumSulfide', 'Sodium sulfide', 'mg'),
('sodiumThiosulfate', 'Sodium thiosulfate', 'mg'),
('stearicAcid', 'Stearic acid', 'mg'),
('strontiumCarbonate', 'Strontium carbonate', 'mg'),
('sulfur', 'Sulfur', 'mg'),
('sulfuricAcid', 'Sulfuric acid', 'ml'),
('tapsoBuffer', 'TAPSO buffer', 'mg'),
('tapsBuffer', 'TAPS buffer', 'mg'),
('temed', 'TEMED', 'ml'),
('tesBuffer', 'TES buffer', 'mg'),
('tricineBuffer', 'Tricine buffer', 'mg'),
('trinitrobenzoicAcid', 'Trinitrobenzoic acid', 'mg'),
('trioctylamine', 'Trioctylamine', 'ml'),
('trisBuffers', 'Tris buffers', 'mg'),
('tropeolinO', 'Tropeolin O', 'mg'),
('tropeolinOo', 'Tropeolin OO', 'mg'),
('tropeolinOoo', 'Tropeolin OOO', 'mg'),
('universalIndicator', 'Universal indicator', 'ml'),
('xylene', 'Xylene', 'ml'),
('zinc', 'Zinc', 'mg'),
('zincChloride', 'Zinc chloride', 'mg'),
('zincNitrate', 'Zinc nitrate', 'mg'),
('zincSulfate', 'Zinc sulfate', 'mg'),
('zirconium', 'Zirconium', 'mg'),
('alphaNaphtholbenzein', 'α-Naphtholbenzein', 'mg'),
('alphaNaphtholphthalein', 'α-Naphtholphthalein', 'mg'),
('alphaNaphthylRed', 'α-Naphthyl red', 'mg')
ON CONFLICT (id) DO NOTHING;